### ISSUE TITLE
Anti AdBlock on ynet

### ISSUE THREAD

**Issue by Yaron10** [easylist/EasyListHebrew#342] opened 2020-08-15 22:46 UTC
https://www.ynet.co.il/digital/mobile/article/BJJWmZxGw#autoplay

Thank you.

**Comment by IsraeliUser** [comment] 2020-08-18 14:01
@mapx-
What do you suggest?

**Comment by mapx-** [comment] 2020-08-18 14:14
I get no anti adb stuff even trying with an ISR ip

**Comment by IsraeliUser** [comment] 2020-08-18 14:24
Go to `https://www.ynet.co.il/digital` and make sure EasyList Hebrew is enabled.

**Comment by mapx-** [comment] 2020-08-18 14:27
a screenshot on your side ?

**Comment by IsraeliUser** [comment] 2020-08-18 15:11
I can't reproduce now. Before I got a message like this: https://github.com/uBlockOrigin/uAssets/issues/6786 .
I guess I will try the same solution if it will come back.

**Comment by Yaron10** [comment] 2020-08-18 21:57
Thank you @IsraeliUser and @mapx-.

I can not reproduce it now either.

**Comment by doclucas** [comment] 2020-09-04 04:04
This issue is back.

**Comment by mapx-** [comment] 2020-09-04 06:08
try

`ynet.co.il##+js(nostif, offsetHeight)`

**Comment by doclucas** [comment] 2020-09-04 06:37
works. thanks :)

**Comment by Yaron10** [comment] 2020-09-04 12:01
I still get the prompt to disable AdBlock.
(Clicking "Close", the page is displayed properly).

Firefox + uBO.

Thank you.

**Comment by IsraeliUser** [comment] 2020-09-05 20:11
@Yaron10 
I can't reproduce.
Try `ynet.co.il##+js(acis, atob, googlefc)`

**Comment by Yaron10** [comment] 2020-09-05 20:22
@IsraeliUser,

I still get it with `ynet.co.il##+js(acis, atob, googlefc)`.

Screenshot taken just now.

![תמונה](https://user-images.githubusercontent.com/10229320/92312940-814f9800-efce-11ea-8c5d-ae77d3cfabef.png)

Thank you.

**Comment by Yaron10** [comment] 2020-09-07 11:30
@IsraeliUser,

Now I get it on their main page too.
https://www.ynet.co.il/home/0,7340,L-8,00.html

![תמונה](https://user-images.githubusercontent.com/10229320/92383211-946d7f80-f116-11ea-8a8b-66a87335c14c.png)

**Comment by IsraeliUser** [comment] 2020-09-07 13:51
Did you disable some of the default filter lists?
Please add a screenshot of your _Filter lists_ menu.
Go to the _Settings menu_  and click on _Reset to default settings..._

**Comment by Yaron10** [comment] 2020-09-07 17:39
After `Reset to default settings` (EasyList Hebrew NOT included), I got the following banner:

![תמונה](https://user-images.githubusercontent.com/10229320/92409470-6b1a1700-f149-11ea-833e-31848ed2d7da.png)

Adding "EasyList Hebrew", I don't get the prompt nor the banner.

It turns out that the "uBlock filters" has the extra important rule.
Can you please track it and add it to "EasyList Hebrew"? - I'd rather not enable "uBlock filters".

Thank you.

**Comment by doclucas** [comment] 2020-09-07 17:46
Did you try adding
'ynet.co.il##+js(nostif, offsetHeight)'?

If so, where did you put it? Screenshot?

**Comment by Yaron10** [comment] 2020-09-07 17:50
I added it to "My Filters".

![תמונה](https://user-images.githubusercontent.com/10229320/92410094-ae758500-f14b-11ea-8f35-994ad54296bb.png)

**Comment by doclucas** [comment] 2020-09-07 18:15
Yeah, it seems uBlock filters are required.
There are certain rules in uBlock filters - Privacy which are being used.
You can see them when you open the console log and launch ynet.

**Comment by Yaron10** [comment] 2020-09-07 18:31
> There are certain rules in uBlock filters - Privacy which are being used.

Enabling "uBlock filters" (NOT - Privacy) solves the problem without `ynet.co.il##+js(nostif, offsetHeight)`.

IMO the relevant rule(s) should be added to "EasyList Hebrew".

Thank you.

**Comment by doclucas** [comment] 2020-09-07 18:50
At first when I launched the logger and didn't see any "uBlock filters" being used, but only filters from "uBlock filters - Privacy" I assumed it requires "uBlock filters" to run.
A bit tricky to reproduce. I just disabled "uBlock filters" and ynet loads fine, while I got the popup earlier.
It seems the popup doesn't always show up?

**Comment by Yaron10** [comment] 2020-09-07 19:10
> A bit tricky to reproduce. I just disabled "uBlock filters" and ynet loads fine, while I got the popup earlier.
It seems the popup doesn't always show up?

That's possible.
On my machine it's quite consistent: I've enabled/disabled "uBlock filters" several times, reloaded https://www.ynet.co.il/home/0,7340,L-8,00.html and the prompt appeared only when "disabled".

**Comment by Yaron10** [comment] 2020-09-07 19:25
@doclucas,

Disabling "uBlock filters" and adding `||fundingchoicesmessages.google.com^$third-party` to "My Filters" blocks the pop-up.
Can you please try it?

**Comment by mapx-** [comment] 2020-09-07 19:30
@Yaron10 just use uBO filters list, it's a very bad idea to run uBO without it

**Comment by Yaron10** [comment] 2020-09-07 19:33
@mapx-,

May I ask why?
Do you mean the **5** uBO lists?

Thanks.

**Comment by mapx-** [comment] 2020-09-07 19:37
Especially uBlock Filters list (the main one) but the others too (the default setup).

Why ? uBO without its own lists is = ZERO (as you already discovered)

**Comment by Yaron10** [comment] 2020-09-07 19:40
> uBO without its own lists is = ZERO (as you already discovered)

I rarely encounter any issues.
Wouldn't it be a "bloat" to enable those lists for a couple of issues?

**Comment by mapx-** [comment] 2020-09-09 12:11
@kobizz you should use uBO (uBlock Origin adblocker) and give up ABP.
uBO is dealing with anti-adblocking and those 2 sites are already fixed in the default setup (including this list `EasyListHebrew`)

**Comment by IsraeliUser** [comment] 2020-09-09 14:46
@Yaron10 
Please use the default setup + EasyList Hebrew. It won't slow down your browser.
EasyList Hebrew included in the default setup if your browser's language is Hebrew.

@mapx- 
Video not working (default setup + EasyList Hebrew)... Can you reproduce?

**Comment by mapx-** [comment] 2020-09-09 14:59
> Video not working

Where is that video ?

**Comment by Yaron10** [comment] 2020-09-09 15:46
@IsraeliUser,

> Please use the default setup + EasyList Hebrew. It won't slow down your browser.

:+1: 

> EasyList Hebrew is included in the default setup if your browser's language is Hebrew.

I'm using the unbranded build (English) with the Hebrew-Language add-on.
EasyList Hebrew is not included with the default settings.

> Video not working.

I can reproduce it.
https://www.ynet.co.il/article/r1Jr9ELNw#autoplay

**Comment by mapx-** [comment] 2020-09-09 16:10
add
```
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=ynet.co.il
@@||ynet.co.il/Common/Api/Scripts/video/videojs.ads.min.js$script,1p
```

**Comment by Yaron10** [comment] 2020-09-09 17:23
@mapx-,

:+1: 
Thank you.

**Comment by gorhill** [comment] 2020-09-12 16:21
@Yaron10 

> Wouldn't it be a "bloat" to enable those lists for a couple of issues?

"uBlock filters" is no different than EasyList, they are both full of filters for sites you will never visit, and yet you are not disabling EasyList because of this. The filter lists enabled by default is the basic requirements to ensure uBO works as intended. Whoever disable any of the default lists will have to deal themselves with the consequences of doing so, we can't offer support for configurations below the basic, minimal one.

**Comment by Yaron10** [comment] 2020-09-12 17:54
@gorhill,

Thank you.

**Closed** 2021-01-10 09:00 UTC
