### ISSUE TITLE
ads 13tv

### ISSUE THREAD

**Issue by shlomi284** [easylist/EasyListHebrew#387] opened 2023-03-08 18:03 UTC
https://13tv.co.il/
new ads after refresh page

**Comment by Hebrew-uBO-User** [comment] 2023-03-18 22:59
@shlomi284 
No ads on my end.
Do you mean
https://user-images.githubusercontent.com/28808501/101383696-2164d800-38c2-11eb-9897-f3f46ab21aac.png
?

@mapx-
It's a redirect page.
skip = דלג
Can it be fixed with uBO?

**Comment by shlomi284** [comment] 2023-03-18 23:12
yes

**Comment by mapx-** [comment] 2023-03-19 08:38
Test:

- clear cookies / storage for that site
- add:

`13tv.co.il##+js(cookie-remover, /^/)`

(initially maybe you should go with ctrl-f5 bypassing the cache)

**Comment by shlomi284** [comment] 2023-03-19 15:56
I added it to my filters and it doesn't work

**Comment by EasyListHebrew** [comment] 2024-05-07 15:20
@mapx- is it fixable or should i close?

**Comment by mapx-** [comment] 2024-05-07 17:09
I cannot reproduce the issue on live page or some [article page](https://13tv.co.il/item/news/politics/security/jvo3w-904046916/)

**Comment by Hebrew-uBO-User** [comment] 2024-05-08 04:26
I'm no longer able to reproduce the issue.

**Closed by Hebrew-uBO-User** 2024-05-08 04:26 UTC
