### ISSUE TITLE
hxcdn.com used for talkbacks and some mail features (walla)

### ISSUE THREAD

**Issue by davidroze** [easylist/EasyListHebrew#279] opened 2017-12-05 18:30 UTC
after the last commit , some of the talkbacks functionality and the mail client calender has been damaged.

**Comment by dani3lL** [comment] 2017-12-06 07:21
i think that fix didn't do it, i still got issues in the talkbacks (after clearing cache and pulling the updated list).

**Comment by davidroze** [comment] 2017-12-06 09:11
@dani3lL is right , please fix this i'm not using the list now and i get all of those crapy ads.

**Comment by IsraeliAdblocker** [comment] 2017-12-06 09:41
fixed in the last commit, please send screenshot + link of any specific feature that isn't working.

**Comment by davidroze** [comment] 2017-12-06 12:17
![screenshot](https://user-images.githubusercontent.com/34282809/33661280-d0e86a2e-da8f-11e7-9152-9db45fd4d4df.png)
you can see in the pic that i can't view the comments and the "submit" isn't working.
without the easylist everything is working fine and if i whitelist hxcdn.com everything is working.

**Comment by dani3lL** [comment] 2017-12-08 18:31
Any updates? Or should I whitelist the domain? (I’m using ublock any specific syntax for whitelisting the domain?)

**Comment by IsraeliUser** [comment] 2017-12-09 22:45
I can't reproduce.
Please provide a screenshot of uBlock Origin's Logger.

**Comment by IsraeliAdblocker** [comment] 2017-12-12 10:19
can't reproduce either, tested both ABP and Adblock.

**Closed** 2019-02-17 19:58 UTC
